import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { FaPlus } from "react-icons/fa6";
import PlusButton from "@/components/PlusButton";
import { SessionProvider } from "next-auth/react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen">
          <div className="container max-w-[1566px] ml-auto mr-auto pl-[80px] pr-[80px]">
          <NavBar></NavBar>
          <SessionProvider>
          {children}          

          </SessionProvider>
          <Footer></Footer>          
          </div>
        </div>
      </body>
    </html>
  );
}
